# Generated by Django 4.2.7 on 2023-11-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='floor',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
